spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/init_my_db.sql
  application:
    name: ms-transaction-api
  datasource:
    url: jdbc:h2:mem:transactiondb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
logging:
  level:
    root: INFO
    com.transaction.api: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.h2.database: DEBUG
    org.springframework.boot.web: INFO